### ISSUE TITLE
keymappable

### ISSUE THREAD

**Issue by bennypowers** [johmsalas/nvim-lua-string-case#1]
Hey, this is amazing!

would you consider making the plugin key mappable using regular vimscript keymapping tables?

**Comment by johmsalas** [comment]
Hi @bennypowers!, this is my first plugin and also my first issue :)

It is in my personal TODO list, to add support for custom keymapping via `nvim_set_keymap`. Would it work for vimscript? This is a Lua plugin, so it will not work on vim, only Neovim

**Comment by johmsalas** [comment]
Added custom key binding support. Let me know if it solves your requirement or if you can provide other details that'd be great

https://github.com/johmsalas/nvim-lua-string-case/blob/10a3e75b3bc1ee0d9bf6a4dc8644634b509d6c31/README.md?plain=1#L95
